import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import WorkoutsProvider from "@/context/WorkoutsContext";
import { ToastContainer } from "react-toastify/unstyled";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <WorkoutsProvider>
          <Navbar />
          {children}
          <h2 className="font-bold text-6xl bg-pink-300 text-center">Footer</h2>
           <ToastContainer />
        </WorkoutsProvider>
      </body>
    </html>
  );
}
